---
title: "Temperature conditions during the experiment"
author: "Ana Palacio"
date: "July 26, 2017"
output:
  html_document:
    fig_height: 2
    fig_width: 3.5
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


# 1. Libraries and settings

```{r}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(ggthemes)
    library(lubridate)

# Default ggplot settings

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

# 2. Import the temperature data

```{r}
Temperature<-read.csv("Day_Tem.csv", header = T)

Temperature$Period<-factor((Temperature$Period),levels=c
              ("Acer","Ofav-Ssid","Nutrients", "Ramping up",
                "Bleaching","Ramping down", "Recovery2"))
  
# Temperature data available from each treatment-replicate-day
Periods.days <- ddply (Temperature, .(Period, Treatment),summarise,
                Dmin = min (Day, na.rm = F), 
                Dmax = max (Day, na.rm = F))
Periods.days

Temperature.82<-subset(Temperature, Day=="82")
Temperature.111<-subset(Temperature, Day=="111")

Periods.82 <- ddply (Temperature.82, .(Treatment),summarise,
                Tmean = mean (Temperature, na.rm = F), 
                Tmin = min (Temperature, na.rm = F), 
                Tmax = max (Temperature, na.rm = F))
Periods.82

Periods.82 <- ddply (Temperature.82, .(Day),summarise,
                Tmean = mean (Temperature, na.rm = F), 
                Tmin = min (Temperature, na.rm = F), 
                Tmax = max (Temperature, na.rm = F))
Periods.82

Periods.82 <- ddply (Temperature.82, .(Day),summarise,
                Tmean = mean (Temperature, na.rm = F), 
                Tsd = sd (Temperature, na.rm = F))
Periods.82

Periods.110 <- ddply (Temperature.111, .(Day),summarise,
                Tmean = mean (Temperature, na.rm = F), 
                Tsd = sd (Temperature, na.rm = F))
Periods.110

```

# 3. Glance at temperature conditions during each period of the experiment:
* during recovery from collection and fragmentation and 
* during the experiment (nutrient addition, ramping up, and bleaching)
* during recovery from bleaching

```{r}
Temperature_Periods_R<- ggplot(Temperature, aes (Day, Temperature, 
                                               colour=factor(Period))) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") +   ggthe_bw +
  xlab("Days in the experiment")  + guides(colour=guide_legend("Period")) +
  ylab("Temperature (C)") + facet_grid(Replicate~.) 
Temperature_Periods_R

Summary_Period <- ddply (Temperature, .(Period),summarise, 
                              Temp = mean (Temperature, na.rm = T),
                              Tsd  = sd (Temperature, na.rm = T), 
                              Tmax = max (Temperature, na.rm = T),
                              Tmin = min (Temperature, na.rm = T))
Summary_Period
  
Summary_Tanks <- ddply (Temperature, .(Period, Treatment, Replicate),summarise, 
                             Temp = mean (Temperature, na.rm = T),
                             Tsd  = sd (Temperature, na.rm = T), 
                             Tmax = max (Temperature, na.rm = T),
                             Tmin = min (Temperature, na.rm = T))
Summary_Tanks
```


```{r}
  
Temperature_BW<- ggplot(Temperature, aes (Day, Temperature, colour=Replicate)) +
    ggthe_bw +
    scale_y_continuous(limits = c(23.9,32.1),
                       name=(expression("Temperature"~(degree*C))),
                       breaks = seq(24, 32, 1),  
                       expand = c(0, 0)) +
    scale_x_continuous(name="Days in the experiment",
                       limits = c(0,113),
                       breaks = seq(0, 113, 15),  
                       expand = c(0, 0))+
  
    annotate("segment", x = 2, xend = 91, y = 25, yend = 25,
              colour = "black", linetype=2)+
    annotate("segment", x = 79, xend = 90, y = 25.3, yend = 27,
              colour = "black", linetype=3)+
    annotate("segment", x = 91, xend = 113, y = 27, yend = 27,
              colour = "black", linetype=3)+

    annotate("text", x= c(46, 82, 103), y = 24.5, 
             label=c("Nutrient addition", "Ramping up", "Heat"), size=3) +
    theme(legend.position=c(0.2, 0.7)) +
    scale_colour_manual(values = c("black","gray"))+
    stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
    stat_summary(fun.y=mean, geom="line") 
Temperature_BW
  
# ggsave(file="Outputs/Figure_1_Experiment_a.svg", dpi = 300, plot=Temperature_BW, width=3.5, height=2)
  
```

# Figure 1: Experimental conditions

```{r}
  
  Temperature_BW2<- ggplot(Temperature, aes (Day, Temperature, colour=Replicate)) + ggthe_bw +
  scale_y_continuous(limits = c(24,33.4),
                       name=(expression("Temperature"~(degree*C))),
                       breaks = seq(24, 32, 1),  
                       expand = c(0, 0)) +
  scale_x_continuous(name="Days in the experiment",
                       limits = c(-1,114),
                       breaks = seq(0, 113, 15),  
                       expand = c(0, 0))+
  
    annotate("segment", x = 2, xend = 91, y = 25, yend = 25,
              colour = "black", linetype=2)+
    #annotate("segment", x = 79, xend = 90, y = 26, yend = 26,
     #         colour = "black", linetype=4)+
    #annotate("segment", x = 91, xend = 113, y = 27, yend = 27,
     #         colour = "black", linetype=3)+

    annotate("text", x= c(46, 84, 101), y = c(24.5,25.5,24.5), 
             label=c("Nutrient treatments (A, N, N+P)", " ", " "), size=3) +
  annotate("text", x= c(46, 99), y = c(32.5,32.5), 
             label=c("Control temperature (C) ", 
                     "Heat stress (H)"), size=3) +
  annotate("segment", x = 2, xend = 78, y = 32, yend = 32,
              colour = "black", linetype=1)+
  annotate("segment", x = 91, xend = 113, y = 32, yend = 32,
              colour = "black", linetype=1)+
    theme(legend.position=c(0.2, 0.6),
          legend.text=element_text(size=8)) +
    scale_colour_manual(values = c("black","gray"))+
    stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
    stat_summary(fun.y=mean, geom="line") +
  annotate("point",x=c(1, 75, 100, 111), y=c(25.3), 
           shape=21, size=2, fill="white") +
  annotate("point",x=c(82, 111), y=c(25.3, 25.8), 
           shape=21, size=2, fill="white")+
  annotate("point",x=c(82, 111), y=c(25.3, 25.8), 
           shape=4, size=2)+
# Labels
 annotate("point",x=c(3, 3), y=c(27, 27.5), 
           shape=21, size=2, fill="white")+
  annotate("point",x=c(3), y=c(27.5), 
           shape=4, size=2)+
  annotate("text", x= c(32,30), y = c(27,27.5), 
             label=c("Non-sacrificial samples", 
                     "Sacrificial samples"), size=3)
  
  Temperature_BW2
  
  # ggsave(file="Outputs/Figure_1_Experiment_c.svg", plot=Temperature_BW2, dpi = 300, width=4, height=2.5)
  
```


