---
title: "Acer SH Nutrients"
author: "Ana Palacio"
date: "July 26, 2019"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# General project set-up 

```{r libraries , results="hide"}

    getwd()

    # Get all libraries and sources required to run the script
        library(plyr)
        library(dplyr)
        library(reshape2)
        library(ggplot2)
        library(ggthemes)
        library(lme4)
        library(lmerTest)
        library(emmeans)
        library(scales)
        library(skimr)


# Default ggplot settings

Fill.colour<-scale_colour_manual(values = c("black", "gray70", "gray35"))

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

#---------------------------------------------------------------------------------
## 1. DATA Exploration

    
### 1.1. Select qPCR info and define factors
 

```{r VariablesToUse}

# Import S/H cell ratio data
Acer.data<-read.csv("Outputs/SH_cell_ratio.csv")

qPCR.variables  <- Acer.data[, c("Sample", "Treatment", "Replicate", "Genotype", "Fragment", "Date", "Days", "A.Acer", "logA.SH")]

# Variable types 
str(qPCR.variables)
  qPCR.variables$Colony<-as.factor(qPCR.variables$Genotype)
  qPCR.variables$DaysF<-as.factor(qPCR.variables$Days)

  summary(qPCR.variables)
  #skim(qPCR.variables)

```  

### 1.2. Exploratory graphs

```{r}
logSHTreatment <- ggplot(qPCR.variables, aes(Date, logA.SH, colour=factor(Treatment))) +
       # geom_jitter(aes(colour=factor(Treatment))) +
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
       stat_summary(fun.y=mean, geom="line", size =1) +
       theme_gdocs() 
logSHTreatment + facet_wrap(~Genotype)

# Removing weird points (whole fragment samples, between bleaching) and colonies not used (F)
    qPCR.variables_2<-subset(qPCR.variables, Date!="2018-02-05")
    qPCR.variables_2<-subset(qPCR.variables_2, Date!="2017-12-14")
    qPCR.variables_2<-subset(qPCR.variables_2, Date!="2018-03-01")
    qPCR.variables_2<-subset(qPCR.variables_2, Date!="2018-03-02")
    qPCR.variables_2<-subset(qPCR.variables_2, Date!="2018-03-03")
    qPCR.variables_2<-subset(qPCR.variables_2, Colony!="F")
    #qPCR.variables_2<-subset(qPCR.variables_2, Colony!="Yellow")
    
    ## Genotype information
    MOTE<-read.csv("Genotype_Info.csv", header = TRUE)
    qPCR.variables_2<-merge(qPCR.variables_2, MOTE, 
                            by="Genotype", all.x=TRUE)
    
    qPCR.variables_2$MoteGen<-factor(as.character(
      qPCR.variables_2$MoteGen), 
                             levels=c("G_48", "G_62","G_31", 
                                      "G_08","G_07", "G_50"))  # D dominance order


logSH_Colony<- ggplot(qPCR.variables_2, aes (Date, logA.SH, colour=factor(Treatment))) +
  geom_jitter(alpha=0.3)+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  stat_summary(fun.y=mean, geom="line") +   theme_gdocs()
logSH_Colony + facet_grid (MoteGen~.)

logSH_Colony<- ggplot(qPCR.variables_2, aes (Date, logA.SH, colour=factor(Colony))) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  stat_summary(fun.y=mean, geom="line") +   theme_gdocs()
logSH_Colony + facet_grid (Treatment~Replicate) +
  theme(legend.position = "none")
```

# Figure 4a

```{r}
 # NOT log 10
Figure4 <- ggplot (qPCR.variables_2, aes(Days, A.Acer, colour=Treatment,
                                          shape=Treatment)) + 
    ggthe_bw + Fill.colour+ ggtitle("a.")+
    theme(legend.position=c(0.2, 0.3),
        legend.title = element_blank()) +
       #geom_jitter(aes(colour=factor(Replicate))) +
     
        
      annotate("segment", x = 2, xend = 91, y = 0.01, yend = 0.01,
                  colour = "gray90", linetype=1)+
      annotate("segment", x = 79, xend = 91, y = 0.01, yend = 0.04,
                  colour = "gray90", linetype=1)+
      annotate("segment", x = 91, xend = 110, y = 0.04, yend = 0.04,
                  colour = "gray90", linetype=1)+
      annotate("text", x = 45, y = 0.02, label = "Nutrients", size=3)+
      annotate("text", x = 99, y = 0.02, label = "H", size=3)+
  
    scale_y_continuous(breaks = seq(0, 0.4, 0.05),
                       #limits = c(0,0.5),
                       expand = c(0.01,0.01),
                   name=("Symbiont to host cell ratio  (S/H)")) +
    scale_x_continuous(name="Days in the experiment",
                         limits = c(-2,113),
                         breaks = seq(0, 110, 15),  
                         expand = c(0, 0)) +
    stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
                    position = position_dodge(width = 2), width = 2 )+
    stat_summary(fun.y=mean, geom="point", size =2, alpha=0.8, 
                   position = position_dodge(width = 2)) +
    stat_summary(fun.y=mean, geom="line", 
                    position = position_dodge(width = 2))

Figure4

Figure4_gen<- ggplot (qPCR.variables_2, aes(Days, logA.SH , colour=Treatment,
                                          shape=Treatment)) + 
    ggthe_bw + Fill.colour+ 
    theme(legend.position="bottom",
       legend.title = element_blank()) +
        
      annotate("segment", x = 2, xend = 91, y = 0.01, yend = 0.01,
                  colour = "gray90", linetype=1)+
      annotate("segment", x = 79, xend = 91, y = 0.01, yend = 0.04,
                  colour = "gray90", linetype=1)+
      annotate("segment", x = 91, xend = 110, y = 0.04, yend = 0.04,
                  colour = "gray90", linetype=1)+
      annotate("text", x = 45, y = 0.02, label = "Nutrients", size=3)+
      annotate("text", x = 99, y = 0.02, label = "H", size=3)+
  
    scale_y_continuous(breaks = seq(-2, -0.1, 0.25),
                       limits = c(-2, -0.1),
                       expand = c(0,0),
                  name=("Symbiont to host cell ratio  - log 10(S/H)")) +
    scale_x_continuous(name="Days in the experiment",
                         limits = c(-2,113),
                         breaks = seq(0, 110, 30),  
                         expand = c(0, 0)) +
    stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", width = 20, 
                    position = position_dodge(width = 2))+
    stat_summary(fun.y=mean, geom="point", size =2, alpha=0.5, 
                   position = position_dodge(width = 2)) +
    stat_summary(fun.y=mean, geom="line", 
                    position = position_dodge(width = 2))+
  facet_grid(~MoteGen)

Figure4_gen
  
  #ggsave(file="Outputs/Fig_4_SH_Acer.svg", plot=Figure4, width=3.5, height=3)
  #ggsave(file="Outputs/Fig_S3_SH_Acer_Genotype.svg", plot=Figure4_gen, width=6.1, height=3.5)

```

# 2. LMER model 

```{r}
 
# Day as factor

LM_Acer.qpCR<-lmer(logA.SH ~ Treatment * DaysF + (1|Replicate) + (1|Colony/Fragment), data= qPCR.variables_2)
step(LM_Acer.qpCR)
anova(LM_Acer.qpCR)
ranova(LM_Acer.qpCR)
summary(LM_Acer.qpCR)

LM_Acer.qPCR2<-lmer(logA.SH ~ Treatment * DaysF + (1|Colony),
                      data= qPCR.variables_2)
step(LM_Acer.qPCR2)

# Multicomp
    Acer.SH.emm<-emmeans(LM_Acer.qPCR2, ~Treatment + DaysF)
      contrast(Acer.SH.emm, "tukey")
      pairs(Acer.SH.emm) # same than contrast(Acer.YII.emm, "tukey")
    Acer.SH_groups<-cld(Acer.SH.emm, by=NULL) # compact-letter display
    Acer.SH_groups<-Acer.SH_groups[order(Acer.SH_groups$Day, Acer.SH_groups$Treatment), ]
    Acer.SH_groups
    write.csv(Acer.SH_groups, "Outputs/Multicomp_AcerSH.csv", row.names = F)
      
      
# Effect plot options
emmip(LM_Acer.qPCR2, ~DaysF|Treatment, CIs = TRUE, aes(Colony=factor(Treatment))) + theme_gdocs() # interaction plot of predictions

# No-log10 data
LM_Acer.qPCR3<-lmer(A.Acer ~ Treatment * DaysF + (1|Colony),
                      data= qPCR.variables_2)
Acer.SH.emm2<-emmeans(LM_Acer.qPCR3, ~Treatment + DaysF)
      contrast(Acer.SH.emm2, "tukey")


```

Only nutrients 

```{r Only_nutrients}
############################
# Only nutrients

qPCR.nutrients<-subset(qPCR.variables_2, qPCR.variables_2$Days<80)

logSHTreatment <- ggplot(qPCR.nutrients, aes(Days, (A.Acer), colour=factor(Treatment))) +
       # geom_jitter(aes(colour=factor(Replicate))) +
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
                    position = position_dodge(width = 1), width = 0.2 )+
      stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5, 
                   position = position_dodge(width = 1)) +
       stat_summary(fun.y=mean, geom="line", size =1, alpha=0.5) + 
       theme_gdocs() 

logSHTreatment + ylab("Relative (A/H)") + xlab("Days in nutrient treatment") +  
      theme(axis.title.y=element_text(size=12), legend.position="none")
                       

logSHTreatment <- ggplot(qPCR.nutrients, aes(Days, logA.SH, colour=factor(Treatment))) +
       # geom_jitter(aes(colour=factor(Replicate))) +
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
                    position = position_dodge(width = 1), width = 0.2 )+
      stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5, 
                   position = position_dodge(width = 1)) +
       stat_summary(fun.y=mean, geom="line", size =1, alpha=0.5) + 
       theme_gdocs() 

logSHTreatment + ylab("log10 (A/H)") + xlab("Days in nutrient treatment") +  
      theme(axis.title.y=element_text(size=12), legend.position="none")

```

Bleaching

```{r Bleaching}
############################
# Bleaching

qPCR.bleaching<-subset(qPCR.variables_2, qPCR.variables_2$Days>70)

Bleaching <- ggplot(qPCR.bleaching, aes(Days, (A.Acer), colour=factor(Treatment))) +
       # geom_jitter(aes(colour=factor(Replicate))) +
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
                    position = position_dodge(width = 1), width = 0.2 )+
      stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5, 
                   position = position_dodge(width = 1)) +
       stat_summary(fun.y=mean, geom="line", size =1, alpha=0.5) + 
       theme_gdocs() 

Bleaching + ylab("Relative (A/H)") + xlab("Days in nutrient treatment") +  
      theme(axis.title.y=element_text(size=12), legend.position="none")
                       

Bleaching <- ggplot(qPCR.bleaching, aes(Days, logA.SH, colour=factor(Treatment))) +
       # geom_jitter(aes(colour=factor(Replicate))) +
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
                    position = position_dodge(width = 1), width = 0.2 )+
      stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5, 
                   position = position_dodge(width = 1)) +
       stat_summary(fun.y=mean, geom="line", size =1, alpha=0.5) + 
       theme_gdocs() 

Bleaching + ylab("log10 (A/H)") + xlab("Days in nutrient treatment") +  
      theme(axis.title.y=element_text(size=12), legend.position="none")

# Bleaching model 
    M_Acer.qpCR<-lmer(logA.SH ~ Treatment * DaysF + (1|Replicate) + (1|Colony/Fragment), data= qPCR.bleaching)
    step(LM_Acer.qpCR)
    anova(LM_Acer.qpCR)
    ranova(LM_Acer.qpCR)
    summary(LM_Acer.qpCR)
    
    LM_Acer.qPCR2<-lmer(logA.SH ~ Treatment + DaysF + (1|Colony),
                          data= qPCR.variables_2)
    step(LM_Acer.qPCR2)
    
    
    # Multicomp
        Acer.SH.emm<-emmeans(LM_Acer.qPCR2, ~Treatment + DaysF)
          contrast(Acer.SH.emm, "tukey")
          pairs(Acer.SH.emm) # same than contrast(Acer.YII.emm, "tukey")
        Acer.SH_groups<-cld(Acer.SH.emm, by=NULL) # compact-letter display
        Acer.SH_groups<-Acer.SH_groups[order(Acer.SH_groups$Day, Acer.SH_groups$Treatment), ]
        Acer.SH_groups
        write.csv(Acer.SH_groups, "Outputs/Multicomp_AcerSH.csv", row.names = F)
          
          
    # Effect plot options
    emmip(LM_Acer.qPCR2, ~DaysF|Treatment, CIs = TRUE, aes(Colony=factor(Treatment))) + theme_gdocs() # interaction plot of predictions
```
