---
title: "Changes in Symbiodiniaceae/cm2 and Chl-a/cm2 in elevated nutrients and heat stress"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7)
```

# General project set-up 

```{r libraries, results="hide"}

# Load libraries and sources required to run the script
    library(tidyverse)
library(plyr)
#library(plotly)
#library(GGally)
    library(ggthemes)
    library(gridExtra)
    library(lmerTest)
    library(emmeans)
    library(multcomp)
    library(multcompView)
    library(emmeans)
    library(effects)


# Default ggplot settings

    Fill.colour<-scale_colour_manual(values = c("black", "gray70", "gray35"))

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

# Read data and organize factors


```{r cars}
# Read data
  data<-read.csv("3.All_Blast.csv")
  summary (data)
  
# Organize factors  
  data$Genotype <- as.factor(paste(data$Spp, data$Colony, sep = "_"))
  data$Fragment <- as.factor(paste(data$Spp, data$Core, sep = "_"))
  data$Rep <- as.factor(data$Rep)
  data$Date<-as.Date(data$Date, "%Y-%m-%d")
  data$Days<-(as.numeric(data$Date) -17485)
  data$DaysF<-(as.factor(data$Days))
  data$Treatment <- as.character(data$Treatment)
  data$Treatment[data$Treatment == "Control"] <- "A"
  data$Treatment[data$Treatment == "NP"] <- "N+P"
  data$Treatment <- as.factor(data$Treatment)
  summary (data)

# Remove the sick guy
data <- data[!(data$Date == "2018-02-15"), ]

# Remove genotype not used
data <- data[!(data$Colony == "A.cer_F"), ]

# Remove unbalanced genotypes
data <- data[!(data$Colony == "A.cer_Red and Yellow"), ]
data <- data[!(data$Colony == "A.cer_Yellow"), ]
data <-droplevels(data)

# Chl by Symbiont
data$Chl.Sym<-((data$Chl_a)/(data$Sym.cm2))
summary(data$Genotype)

# Subset data
Acer.data<-filter(data, Spp=="A.cer")
Ofav.data<-filter(data, Spp=="O.fav")
Ssid.data<-filter(data, Spp=="S.sid")
```

# Explore/Plots

## Symbiodiniaceae

```{r}
# Graphs to initially explore data
SymDen<- ggplot(data, aes(DaysF, Sym.cm2, colour=Treatment)) +
    #geom_jitter(aes(colour=factor(Treatment))) +
    geom_boxplot()+ Fill.colour+
    #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(0.8))+
    ggthe_bw + facet_grid(Spp~., scales = "free_y" )
SymDen

Sym_Colony<- ggplot(data, aes (Days, Sym.cm2, colour=Colony)) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
               position = position_dodge(width = 1), width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") +   theme_gdocs()+
  geom_point(alpha=0.5) + facet_grid (Spp~Treatment, scales="free")
Sym_Colony


Sym_Treatment<- ggplot(data, aes (Days, Sym.cm2, colour=Treatment,
                                   shape=Treatment)) + ggthe_bw +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
               position = position_dodge(width = 3), width = 0.2 )+
  stat_summary(fun.y=mean, geom="line", 
               position = position_dodge(width = 3)) + 
  stat_summary(fun.y=mean, geom="point",
               position = position_dodge(width = 3)) + 
    scale_x_continuous(breaks=c(82, 113)) + Fill.colour +   
  facet_wrap (~Spp, scales="free_y")+
  ylab("Symbiodiniaceae (106 cells / cm2)")
Sym_Treatment

Sy.Summary <- plyr::ddply (data, . (Spp, Treatment, Days),
              summarise,
              Sy_mean = mean (Sym.cm2, na.rm = T),
              Sy_sd = sd (Sym.cm2, na.rm = T))
Sy.Summary

```

## Chlorophyll-a

```{r}
Chl<-ggplot(data, aes(DaysF, Chl_a, colour=Treatment)) +
  #geom_jitter(aes(colour=factor(Treatment))) +
  geom_boxplot()+ Fill.colour+
  #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(0.8))+
  ggthe_bw + facet_grid(Spp~., scales = "free_y" )
Chl

Chl_Treatment<- ggplot(data, aes (Days, Chl_a, colour=Treatment,
                                  shape=Treatment)) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
               position = position_dodge(width = 3), width = 0.2 )+
  stat_summary(fun.y=mean, geom="line", 
               position = position_dodge(width = 3)) + 
  stat_summary(fun.y=mean, geom="point", 
               position = position_dodge(width = 3)) + ggthe_bw + ylab("Chlorophyll-a (ug / cm2)") + 
  scale_x_continuous(breaks=c(82, 113)) + Fill.colour +
    facet_wrap (~Spp)
Chl_Treatment

Chl.Summary <- plyr::ddply (data, . (Spp, Treatment, Days),
              summarise,
              Chl_mean = mean (Chl_a, na.rm = T),
              Chl_sd = sd (Chl_a, na.rm = T))
Chl.Summary

```

## Only Acer plots (figure 4)

```{r}
AcerSym_Treatment<- ggplot(Acer.data, aes (Days, Sym.cm2, colour=Treatment,
                                   shape=Treatment)) + ggthe_bw +
    theme(legend.position = c(0.7, 0.8))+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
               position = position_dodge(width = 3), width = 0.2 )+
  stat_summary(fun.y=mean, geom="line", 
               position = position_dodge(width = 3)) + 
  stat_summary(fun.y=mean, geom="point",
               position = position_dodge(width = 3)) + 
    scale_x_continuous(breaks=c(82, 113)) + Fill.colour +   
    ylab("Symbiodiniaceae (106 cells / cm2)") +
  ggtitle("b.")
AcerSym_Treatment

AcerChl_Treatment<- ggplot(Acer.data, aes (Days, Chl_a, colour=Treatment,
                                   shape=Treatment)) + ggthe_bw +
  theme(legend.position = c(0.7, 0.8))+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", 
               position = position_dodge(width = 3), width = 0.2 )+
  stat_summary(fun.y=mean, geom="line", 
               position = position_dodge(width = 3)) + 
  stat_summary(fun.y=mean, geom="point",
               position = position_dodge(width = 3)) + 
    scale_x_continuous(breaks=c(82, 113)) + Fill.colour +   
    ylab("Chlorophyll-a (ug / cm2)")+
  ggtitle("c.")
AcerChl_Treatment
```

```{r}
#grid.arrange(AcerSym_Treatment,AcerChl_Treatment,ncol=2,nrow=1)

ggsave(file="Outputs/Acer_Blastate.svg", plot=grid.arrange(AcerSym_Treatment,AcerChl_Treatment,ncol=2,nrow=1), width=3.5, height=3)

#ggsave(file="Outputs/Fig_4_SH_Acer.svg", plot=Figure4, width=3.5, height=3)
```


```{r }

grid.arrange(Sym_Treatment,Chl_Treatment,ncol=1,nrow=2)

ggsave(file="Outputs/SBlastate.svg", plot=grid.arrange(Sym_Treatment,Chl_Treatment,ncol=1,nrow=2),
       width=5.0, height=5)


Chl.S<-ggplot(data, aes(DaysF, Chl.Sym, colour=Treatment)) +
  #geom_jitter(aes(colour=factor(Treatment))) +
  geom_boxplot()+ Fill.colour+
  #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(0.8))+
  ggthe_bw + facet_grid(Spp~., scales = "free_y" )
Chl.S

## Chl_a and Sym density correlation 
    Ch_a.Sym <- ggplot(data, aes(Sym.cm2/1000000,
                      Chl_a, colour=factor(Treatment), shape=Spp)) +   
      geom_smooth(method=lm, colour="black", se=T) + 
      geom_point() + ggthe_bw + Fill.colour
    Ch_a.Sym
    
    Ch_a.Sym + facet_grid(~Date)

```


```{r}
Acer.data<-filter(data, Spp=="A.cer")
```



# Test normality 

```{r}
# Zoox.cm2
  shapiro.test(data$Sym.cm2) # Not normal
  ggplot() + geom_histogram(aes(x=Sym.cm2), data=data)

# Chl-a.cm2 
  shapiro.test(data$Chl_a) # Not normal
  ggplot() + geom_histogram(aes(x=Chl_a), data=data)
  
# Chl-a.Sym   
  shapiro.test(data$Chl.Sym) # Not normal
  ggplot() + geom_histogram(aes(x=Chl.Sym), data=data)

# Transformations 
    data$Zoox.sq<-sqrt(data$Sym.cm2)
    data$lnSym<- log(data$Sym.cm2)
    data$Chl.sq<-sqrt(data$Chl_a)
    data$Chl.Sym.sq<-sqrt(data$Chl.Sym)

# Normality again
  shapiro.test(data$Zoox.sq)# Still not Normal
  ggplot() + geom_histogram(aes(x=Zoox.sq), data=data)
  
  shapiro.test(data$lnSym)# Better, but still not Normal
  ggplot() + geom_histogram(aes(x=lnSym), data=data)
  
  
  shapiro.test(data$Chl.sq)# Normal
  ggplot() + geom_histogram(aes(x=Chl.sq), data=data)
  
  shapiro.test(data$Chl.Sym.sq) # Not normal
  ggplot() + geom_histogram(aes(x=Chl.Sym.sq), data=data)
```
 
# Models

## All spp

```{r}

#Symbionts

LMER_Sym0<-lmer(Sym.cm2 ~ Treatment * Spp * DaysF + 
               (1|Rep) + (1|Spp/Colony), REML=TRUE,
               data=data, na.action=na.omit)
anova(LMER_Sym0)
ranova(LMER_Sym0)
step(LMER_Sym0)
summary(LMER_Sym0)

LMER_Sym<-lmer(Sym.cm2 ~ Treatment * Spp * DaysF + 
               (1|Spp/Colony), REML=TRUE,
               data=data, na.action=na.omit)
anova(LMER_Sym)
ranova(LMER_Sym)
step((LMER_Sym))
summary(LMER_Sym)

LMER_Sym2<-lmer(lnSym ~ Treatment * Spp * DaysF + 
                 (1|Spp/Colony),REML=TRUE,
                data=data, na.action=na.omit)
anova(LMER_Sym2)
ranova(LMER_Sym2)
step((LMER_Sym2))
summary(LMER_Sym2)

# Spp have different sym/cm2 and interactions. Split data    
  
# Chla
LMER_Chla0<-lmer(Chl.sq ~ Treatment * Spp * DaysF + 
                 (1|Rep) + (1|Spp/Colony), 
                data=data, na.action=na.omit)
anova(LMER_Chla0)
ranova(LMER_Chla0)
step(LMER_Chla0)
summary(LMER_Chla0)

LMER_Chla<-lmer(Chl.sq ~ Treatment * Spp * DaysF + 
                + (1|Spp/Colony), 
                data=data, na.action=na.omit)
anova(LMER_Chla)
ranova(LMER_Chla)
step(LMER_Chla)
summary(LMER_Chla)

 Sym_All.Summary <- plyr::ddply (data, . (Spp, Days, Treatment),
              summarise,
              Sym_mean = mean (Sym.cm2, na.rm = T),
              Sym_sd = sd (Sym.cm2, na.rm = T))
  Sym_All.Summary

  Chl_a.Summary <- plyr::ddply (data, . (Spp, Days, Treatment),
              summarise,
              Chl_mean = mean (Chl_a, na.rm = T),
              Chl_sd = sd (Chl_a, na.rm = T))
  Chl_a.Summary

```

## Individual Spp

```{r}
  Acer.data<-subset(data, Spp=="A.cer")
  Ofav.data<-subset(data, Spp=="O.fav")
  Ssid.data<-subset(data, Spp=="S.sid")
```


### Acer

```{r}
summary(Acer.data)

# Zoox.cm2
  shapiro.test(Acer.data$Sym.cm2) # Almost, but not normal
  #ggplot() + geom_histogram(aes(x=Sym.cm2), data=Acer.data)

  shapiro.test(Acer.data$Zoox.sq)# less Normal
  #ggplot() + geom_histogram(aes(x=Zoox.sq), data=Acer.data)

  shapiro.test(Acer.data$lnSym)# less Normal
  #ggplot() + geom_histogram(aes(x=lnSym), data=Acer.data)

  
# Chl-a.cm2 
  shapiro.test(Acer.data$Chl_a) # Normal
  ggplot() + geom_histogram(aes(x=Chl_a), data=Acer.data)
  
  shapiro.test(Acer.data$Chl.sq)# Normal
  ggplot() + geom_histogram(aes(x=Chl.sq), data=Acer.data)
  
```

#### Before and after heat stress

```{r}

# Sym
LMER_Sym_Acer<-lmer(Sym.cm2 ~ Treatment * DaysF + 
                 (1|Rep) + (1|Colony), data=Acer.data, 
                 na.action = na.omit)
    anova(LMER_Sym_Acer)
    ranova(LMER_Sym_Acer)
    step(LMER_Sym_Acer)

LMER_Sym_Acer2<-lmer(Sym.cm2 ~ Treatment + DaysF + 
                 (1|Colony), data=Acer.data, na.action = na.omit)
    anova(LMER_Sym_Acer2)
    ranova(LMER_Sym_Acer2)
    step(LMER_Sym_Acer2)
    
LMER_Sym_Acer3<-lm(Sym.cm2 ~ Treatment + DaysF,
                 data=Acer.data,  na.action = na.omit)
    anova(LMER_Sym_Acer3)
    step(LMER_Sym_Acer3)
    summary(LMER_Sym_Acer3)

# Chl-a
    
LMER_Chla_Acer<-lmer(Chl_a ~ Treatment * DaysF + 
                 (1|Rep) + (1|Colony), data=Acer.data)
    anova(LMER_Chla_Acer)
    ranova(LMER_Chla_Acer)
    step(LMER_Chla_Acer)

LMER_Chla_Acer2<-lmer(Chl_a ~ Treatment * DaysF + 
                 (1|Colony), data=Acer.data)
    anova(LMER_Sym_Acer2)
    ranova(LMER_Sym_Acer2)
    step(LMER_Sym_Acer2)
    
LMER_Chla_Acer3<-lmer(Chl_a ~ DaysF + 
                 (1|Colony), data=Acer.data)
    anova(LMER_Sym_Acer3)
    ranova(LMER_Sym_Acer3)
    step(LMER_Sym_Acer3)
    summary(LMER_Sym_Acer3)
  Acer.Chla.emm<-emmeans(LMER_Chla_Acer2, ~Treatment * DaysF)
  contrast(Acer.Chla.emm, "tukey")
      

# Nutrient treatment is not significant, temperature treatment is. However, data is not balanced (there is not N_Day113 data). Evaluate Day82 alone for nutrient effect?
    
Acer_SymDen<- ggplot(Acer.data, 
                     aes(DaysF, Sym.cm2, colour=Treatment)) +
    #geom_jitter(aes(colour=factor(Treatment))) +
    geom_boxplot()+ Fill.colour+
    #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(0.8))+
    ggthe_bw + facet_grid(Colony~., scales = "free_y" )
Acer_SymDen


```

#### Before heat 

```{r}
Acer.nutrients<-subset(Acer.data, DaysF=="82")
summary(Acer.nutrients)

# Zoox.cm2
  shapiro.test(Acer.nutrients$Sym.cm2) # Normal
  ggplot() + geom_histogram(aes(x=Sym.cm2), data=Acer.nutrients)

  shapiro.test(Acer.nutrients$Zoox.sq)# more Normal
  ggplot() + geom_histogram(aes(x=Zoox.sq), data=Acer.nutrients)

  shapiro.test(Acer.nutrients$lnSym)# more Normal
  ggplot() + geom_histogram(aes(x=lnSym), data=Acer.nutrients)
  
  Sym_82.Summary <- plyr::ddply (Acer.nutrients, . (Treatment),
              summarise,
              Sym_mean = mean (Sym.cm2, na.rm = T),
              Sym_sd = sd (Sym.cm2, na.rm = T))
  Sym_82.Summary

  Chl_a.Summary <- plyr::ddply (Acer.nutrients, . (Treatment),
              summarise,
              Chl_mean = mean (Chl_a, na.rm = T),
              Chl_sd = sd (Chl_a, na.rm = T))
  Sym_82.Summary

# Chl-a.cm2 
  shapiro.test(Acer.nutrients$Chl_a) # Not normal
  ggplot() + geom_histogram(aes(x=Chl_a), data=Acer.nutrients)
  
  shapiro.test(Acer.nutrients$Chl.sq)# Normal
  ggplot() + geom_histogram(aes(x=Chl.sq), data=Acer.nutrients)
 
```

```{r}

```


```{r}

# Sym
LMER_Sym_Acer4<-lmer(Sym.cm2 ~ Treatment +
                 (1|Rep) + (1|Colony), data=Acer.nutrients)
    anova(LMER_Sym_Acer4)
    ranova(LMER_Sym_Acer4)
    step(LMER_Sym_Acer4)

LMER_Sym_Acer5<-lmer(Sym.cm2 ~ Treatment + 
                 (1|Colony), data=Acer.nutrients)
    anova(LMER_Sym_Acer5)
    ranova(LMER_Sym_Acer5)
    step(LMER_Sym_Acer5)
    
LMER_Sym_Acer6<-lmer(lnSym ~ Treatment + 
                  (1|Rep) + (1|Colony), data=Acer.nutrients,
                  na.action=na.omit)
    anova(LMER_Sym_Acer6)
    ranova(LMER_Sym_Acer6)
    step(LMER_Sym_Acer6)
    summary(LMER_Sym_Acer6)

LMER_Sym_Acer6<-lm(lnSym ~ Treatment, data=Acer.nutrients,
                  na.action=na.omit)
    anova(LMER_Sym_Acer6)
    step(LMER_Sym_Acer6)
    summary(LMER_Sym_Acer6)
    
    Sym.emm<-emmeans(LMER_Sym_Acer6, ~Treatment)
    contrast(Sym.emm, "tukey")
    # Effect plot options
    emmip(LMER_Sym_Acer6, ~Treatment, CIs = TRUE) + theme_bw() 

    LMER_Sym_Acer7<-lm(Sym.cm2 ~ Treatment,
                data=Acer.nutrients, na.action=na.omit)
    anova(LMER_Sym_Acer7)
    summary(LMER_Sym_Acer7)
   
    Sym.emm<-emmeans(LMER_Sym_Acer7, ~Treatment)
    contrast(Sym.emm, "tukey")
    # Effect plot options
    emmip(LMER_Sym_Acer7, ~Treatment, CIs = TRUE) + theme_bw() 
    

# Chl-a
    
LMER_Chla_Acer<-lmer(Chl_a ~ Treatment + 
                 (1|Rep) + (1|Colony), data=Acer.nutrients)
    anova(LMER_Chla_Acer)
    ranova(LMER_Chla_Acer)
    step(LMER_Chla_Acer)

LMER_Chla_Acer2<-lm(Chl_a ~ Treatment, data=Acer.nutrients)
    anova(LMER_Chla_Acer2)
    step(LMER_Chla_Acer2)
    summary(LMER_Sym_Acer7)
   
    Chl.emm<-emmeans(LMER_Chla_Acer2, ~Treatment)
    contrast(Chl.emm, "tukey")
    # Effect plot options
    emmip(LMER_Chla_Acer2, ~Treatment, CIs = TRUE) + theme_bw() 
    
    
LMER_Chla_Acer3<-lmer(Chl.sq ~ Treatment + 
                 (1|Rep) + (1|Colony), data=Acer.nutrients)
    anova(LMER_Chla_Acer3)
    ranova(LMER_Chla_Acer3)
    step(LMER_Chla_Acer3)

LMER_Chla_Acer4<-lm(Chl.sq ~ Treatment, data=Acer.nutrients)
    anova(LMER_Chla_Acer4)
    summary(LMER_Chla_Acer4)
   
    Chl.emm<-emmeans(LMER_Chla_Acer4, ~Treatment)
    contrast(Chl.emm, "tukey")
    # Effect plot options
    emmip(LMER_Chla_Acer4, ~Treatment, CIs = TRUE) + theme_bw() 
    
```


# Check this for supp

### Ofav

```{r}
summary(Ofav.data)

# Zoox.cm2
  shapiro.test(Ofav.data$Sym.cm2) # Almost, but not normal
  #ggplot() + geom_histogram(aes(x=Sym.cm2), data=Ofav.data)

  shapiro.test(Ofav.data$Zoox.sq)# less Normal
  #ggplot() + geom_histogram(aes(x=Zoox.sq), data=Ofav.data)

  shapiro.test(Ofav.data$lnSym)# less Normal
  #ggplot() + geom_histogram(aes(x=lnSym), data=Ofav.data)

  
# Chl-a.cm2 
  shapiro.test(Ofav.data$Chl_a) # Normal
  ggplot() + geom_histogram(aes(x=Chl_a), data=Ofav.data)
  
  shapiro.test(Ofav.data$Chl.sq)# Normal
  ggplot() + geom_histogram(aes(x=Chl.sq), data=Ofav.data)
  
```

#### Before and after heat stress

```{r}

# Sym
LMER_Sym_Ofav<-lmer(Sym.cm2 ~ Treatment * DaysF + 
                 (1|Rep) + (1|Colony), data=Ofav.data, 
                 na.action = na.omit)
    anova(LMER_Sym_Ofav)
    ranova(LMER_Sym_Ofav)
    step(LMER_Sym_Ofav)

LMER_Sym_Ofav2<-lmer(Sym.cm2 ~ Treatment + DaysF + 
                 (1|Colony), data=Ofav.data, na.action = na.omit)
    anova(LMER_Sym_Ofav2)
    ranova(LMER_Sym_Ofav2)
    step(LMER_Sym_Ofav2)
    
LMER_Sym_Ofav3<-lm(Sym.cm2 ~ Treatment + DaysF,
                 data=Ofav.data,  na.action = na.omit)
    anova(LMER_Sym_Ofav3)
    step(LMER_Sym_Ofav3)
    summary(LMER_Sym_Ofav3)

# Chl-a
    
LMER_Chla_Ofav<-lmer(Chl_a ~ Treatment * DaysF + 
                 (1|Rep) + (1|Colony), data=Ofav.data)
    anova(LMER_Chla_Ofav)
    ranova(LMER_Chla_Ofav)
    step(LMER_Chla_Ofav)

LMER_Chla_Ofav2<-lmer(Chl_a ~ Treatment + DaysF + 
                 (1|Colony), data=Ofav.data)
    anova(LMER_Sym_Ofav2)
    ranova(LMER_Sym_Ofav2)
    step(LMER_Sym_Ofav2)
    
LMER_Chla_Ofav3<-lmer(Chl_a ~ DaysF + 
                 (1|Colony), data=Ofav.data)
    anova(LMER_Sym_Ofav3)
    ranova(LMER_Sym_Ofav3)
    step(LMER_Sym_Ofav3)
    summary(LMER_Sym_Ofav3)

# Nutrient treatment is not significant, temperature treatment is. However, data is not balanced (there is not N_Day113 data). Evaluate Day82 alone for nutrient effect?
    
Ofav_SymDen<- ggplot(Ofav.data, 
                     aes(DaysF, Sym.cm2, colour=Treatment)) +
    #geom_jitter(aes(colour=factor(Treatment))) +
    geom_boxplot()+ Fill.colour+
    #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(0.8))+
    ggthe_bw + facet_grid(Colony~., scales = "free_y" )
Ofav_SymDen


```

#### Before heat 

```{r}
Ofav.nutrients<-subset(Ofav.data, DaysF=="82")
summary(Ofav.nutrients)

# Zoox.cm2
  shapiro.test(Ofav.nutrients$Sym.cm2) # Normal
  ggplot() + geom_histogram(aes(x=Sym.cm2), data=Ofav.nutrients)

  shapiro.test(Ofav.nutrients$Zoox.sq)# more Normal
  ggplot() + geom_histogram(aes(x=Zoox.sq), data=Ofav.nutrients)

  shapiro.test(Ofav.nutrients$lnSym)# more Normal
  ggplot() + geom_histogram(aes(x=lnSym), data=Ofav.nutrients)

  
# Chl-a.cm2 
  shapiro.test(Ofav.nutrients$Chl_a) # Not normal
  ggplot() + geom_histogram(aes(x=Chl_a), data=Ofav.nutrients)
  
  shapiro.test(Ofav.nutrients$Chl.sq)# Normal
  ggplot() + geom_histogram(aes(x=Chl.sq), data=Ofav.nutrients)
 
```

```{r}

# Sym
LMER_Sym_Ofav4<-lmer(Sym.cm2 ~ Treatment +
                 (1|Rep) + (1|Colony), data=Ofav.nutrients)
    anova(LMER_Sym_Ofav4)
    ranova(LMER_Sym_Ofav4)
    step(LMER_Sym_Ofav4)

LMER_Sym_Ofav5<-lmer(Sym.cm2 ~ Treatment + 
                 (1|Colony), data=Ofav.nutrients)
    anova(LMER_Sym_Ofav5)
    ranova(LMER_Sym_Ofav5)
    step(LMER_Sym_Ofav5)
    
LMER_Sym_Ofav6<-lmer(lnSym ~ Treatment + 
                  (1|Rep) + (1|Colony), data=Ofav.nutrients,
                  na.action=na.omit)
    anova(LMER_Sym_Ofav6)
    ranova(LMER_Sym_Ofav6)
    step(LMER_Sym_Ofav6)
    summary(LMER_Sym_Ofav6)

LMER_Sym_Ofav6<-lm(lnSym ~ Treatment, data=Ofav.nutrients,
                  na.action=na.omit)
    anova(LMER_Sym_Ofav6)
    step(LMER_Sym_Ofav6)
    summary(LMER_Sym_Ofav6)
    
    Sym.emm<-emmeans(LMER_Sym_Ofav6, ~Treatment)
    contrast(Sym.emm, "tukey")
    # Effect plot options
    emmip(LMER_Sym_Ofav6, ~Treatment, CIs = TRUE) + theme_bw() 

    LMER_Sym_Ofav7<-lmer(Sym.cm2 ~ Treatment * Rep,
                data=Ofav.nutrients, na.action=na.omit)
    anova(LMER_Sym_Ofav7)
    summary(LMER_Sym_Ofav7)
   
    Sym.emm<-emmeans(LMER_Sym_Ofav7, ~Treatment)
    contrast(Sym.emm, "tukey")
    # Effect plot options
    emmip(LMER_Sym_Ofav7, ~Treatment, CIs = TRUE) + theme_bw() 
    

# Chl-a
    
LMER_Chla_Ofav<-lmer(Chl_a ~ Treatment + 
                 (1|Rep) + (1|Colony), data=Ofav.nutrients)
    anova(LMER_Chla_Ofav)
    ranova(LMER_Chla_Ofav)
    step(LMER_Chla_Ofav)

LMER_Chla_Ofav2<-lm(Chl_a ~ Treatment, data=Ofav.nutrients)
    anova(LMER_Chla_Ofav2)
    step(LMER_Chla_Ofav2)
    summary(LMER_Sym_Ofav7)
   
    Chl.emm<-emmeans(LMER_Chla_Ofav2, ~Treatment)
    contrast(Chl.emm, "tukey")
    # Effect plot options
    emmip(LMER_Chla_Ofav2, ~Treatment, CIs = TRUE) + theme_bw() 
    
    
LMER_Chla_Ofav3<-lmer(Chl.sq ~ Treatment + 
                 (1|Rep) + (1|Colony), data=Ofav.nutrients)
    anova(LMER_Chla_Ofav3)
    ranova(LMER_Chla_Ofav3)
    step(LMER_Chla_Ofav3)

LMER_Chla_Ofav4<-lm(Chl.sq ~ Treatment, data=Ofav.nutrients)
    anova(LMER_Chla_Ofav4)
    summary(LMER_Chla_Ofav4)
   
    Chl.emm<-emmeans(LMER_Chla_Ofav4, ~Treatment)
    contrast(Chl.emm, "tukey")
    # Effect plot options
    emmip(LMER_Chla_Ofav4, ~Treatment, CIs = TRUE) + theme_bw() 
    
```
