---
title: "New_Acer mortality"
author: "Ana Palacio"
date: "Nov 18, 2019"
output:
  html_document:
    fig_height: 7
    fig_width: 5
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# General project set-up 

```{r libraries, results="hide"}

# Load all libraries and sources required to run the script
    library(tidyverse)
    library(ggthemes)
    library(survival)
    library(survminer)
    #library(rms)
   
# Default ggplot settings

    Fill.colour<-c("black", "gray70", "gray35")

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

Try survival package

```{r}
# Data
    Survival.data<-read.csv("Acer_Mortality.csv", header = TRUE)
    summary(Survival.data)
    summary(Survival.data$Genotype)
    Survival.data$Genotype<-factor(Survival.data$Genotype, 
                                   levels=c("Ac_48", "Ac_62","Ac_31", "Ac_08","Ac_07", "Ac_50"))
    summary(Survival.data$Genotype)
```

```{r}
## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object <- Surv(time = Survival.data$Fu.time_texp, event = Survival.data$Fu.stat_exp)
  surv_object 

# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0 <- survfit(surv_object ~ Genotype, conf.type = "log-log", data = Survival.data)
    summary(fit0)
  # Plot the survival model
    Genotype_only<-ggsurvplot(fit0, data = Survival.data, pval = TRUE,
               risk.table=T, tables.height=0.4, conf.int = T, n.risk   = TRUE )
    Genotype_only

# Only treatment model
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit1 <- survfit(surv_object ~ Treatment, data = Survival.data)
    summary(fit1)
    #coxfit <- coxph(surv_object ~ Treatment, data = Survival.data, ties = 'exact')
    #summary(coxfit)

    # Plot the survival model
    Treatment_Only<-ggsurvplot(fit1, data = Survival.data, pval = TRUE, 
           conf.int = T, risk.table=T, palette=Fill.colour,
           break.time.by=15, xlim=c(0,115), risk.table.y.text = FALSE,
           risk.table.title="Number of fragments at risk")
    Treatment_Only
    #ggsave("Outputs/Fig_2_Surv_Treatment.svg", 
     #      Treatment_Only$plot, width=4, height=3.5,dpi = 300)
    #ggsave("Outputs/Fig_2_Surv_Treatment.pdf", print(Treatment_Only),
     #      width=5, height=6,dpi = 300)


# Treatment and genotype model 1 
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit2 <- survfit(surv_object ~ Genotype + Treatment, data = Survival.data)
    summary(fit2)
    # Plot the survival model
    GenTre_1<-ggsurvplot(fit2, data = Survival.data, pval = TRUE,
           risk.table=T,  tables.height=0.5)
    GenTre_1
    
    ggsurvplot_facet(fit2, data = Survival.data, facet.by="Genotype", 
                     #risk.table=T, tables.height=0.5, 
                 nrow = 6, alpha=1,
                 palette=Fill.colour, linetype=1)


    ggsurvplot_facet(fit2, data = Survival.data, 
                 facet.by="Treatment", 
                 # risk.table=T, tables.height=0.5, 
                 nrow = 3, alpha=0.5,
                 linetype=1)
    
# Treatment and genotype model 2
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit3 <- survfit(surv_object ~ Gen_Treat, data = Survival.data)
    summary(fit3)
    # Plot the survival model
    ggsurvplot(fit3, data = Survival.data, pval = TRUE, conf.int = F,
           risk.table=T,  tables.height=0.5)
    

```

Do not run
```{r}
# fit.coxph0 <- coxph(surv_object ~ Genotype, data = Survival.data)
# ggforest(fit.coxph0, data = Survival.data)
# fit.coxph0

# fit.coxph1 <- coxph(surv_object ~ Treatment, data = Survival.data)
# ggforest(fit.coxph1, data = Survival.data)
# fit.coxph1
# 
# fit.coxph2 <- coxph(surv_object ~ factor(Treatment) + factor (Genotype), data = Survival.data)
# ggforest(fit.coxph, data = Survival.data)
# fit.coxph2
# summary(fit.coxph2)
# 
# fit.coxph3 <- coxph(surv_object ~ factor(Gen_Treat), data = Survival.data)
# ggforest(fit.coxph3, data = Survival.data)
# fit.coxph3
# summary(fit.coxph3)

```

## 2. Remove the Ambient data and run models again

```{r}
# Data
    Survival.data2<-Survival.data[(Survival.data$Treatment!="Ambient"),]
    summary(Survival.data2)
    summary(Survival.data2$Genotype)
    Survival.data2$Genotype<-factor(Survival.data2$Genotype, 
                                   levels=c("Ac_48", "Ac_62","Ac_31", "Ac_08","Ac_07", "Ac_50"))
    summary(Survival.data2$Genotype)
    summary(Survival.data2$Treatment)
    Survival.data2$Treatment<-factor(Survival.data2$Treatment, 
                                   levels=c("N", "N_P"))
```

```{r}
## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object2 <- Surv(time = Survival.data2$Fu.time_texp, event = Survival.data2$Fu.stat_exp)
  surv_object2 

# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0_2 <- survfit(surv_object2 ~ Genotype, conf.type = "log-log", data = Survival.data2)
    summary(fit0_2)
    surv_pvalue(fit0_2)
    coxfit0_2 <- coxph(surv_object2 ~ Genotype, data = Survival.data2, ties = 'exact')
  # Plot the survival model
    Genotype_only2<-ggsurvplot(fit0_2, data = Survival.data2, pval = TRUE,
               risk.table=T, tables.height=0.4, conf.int = T, n.risk = TRUE,
               #risk.table.y.text = FALSE, 
               break.time.by=15, xlim=c(0,115), 
           risk.table.title="Number of A. cervicornis at risk")
    Genotype_only2
    
    #ggsave("Outputs/Fig_2_Surv_Genotype.svg", 
    #       Genotype_only2$plot, width=4.5, height=3.5,dpi = 300)
    #ggsave("Outputs/Fig_2_Surv_Genotype.pdf", print(Genotype_only2),
    #       width=4.5, height=4.5,dpi = 300)

# Only treatment model
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit1_2 <- survfit(surv_object2 ~ Treatment, data = Survival.data2)
    summary(fit1_2)
    surv_pvalue(fit1_2)
    coxfit1_2 <- coxph(surv_object2 ~ Treatment, data = Survival.data2, ties = 'exact')
    #summary(coxfit1_2)

    # Plot the survival model
    Treatment_Only<-ggsurvplot(fit1_2, data = Survival.data2, pval = TRUE, 
           conf.int = T, risk.table=T, palette=Fill.colour)
    Treatment_Only
    
# Treatment and genotype model 1 
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit2_2 <- survfit(surv_object2 ~ Genotype + Treatment, data = Survival.data2)
    summary(fit2_2)
    # Plot the survival model
    GenTre_1_2<-ggsurvplot(fit2_2, data = Survival.data2, pval = TRUE, conf.int = T,
           risk.table=T,  tables.height=0.5)
    GenTre_1_2
    
    ggsurvplot_facet(fit2_2, data = Survival.data2, 
                 facet.by="Genotype", risk.table=T, conf.int = T,
                 tables.height=0.5, nrow = 6, alpha=1,
                 palette=Fill.colour, linetype=1)


    ggsurvplot_facet(fit2_2, data = Survival.data2, 
                 facet.by="Treatment", risk.table=T, conf.int = T,
                 tables.height=0.5, nrow = 3, alpha=0.5,
                 linetype=1)
    

```

```{r}
fit.coxph0_2 <- coxph(surv_object2 ~ Genotype, data = Survival.data2)
HazardRatio<-ggforest(fit.coxph0_2, data = Survival.data2)
fit.coxph0_2

#ggsave("Outputs/Fig_S1_HazardRatio.svg", HazardRatio, width=6, height=4,dpi = 300)
    
fit.coxph1_2 <- coxph(surv_object2 ~ Treatment, data = Survival.data2)
ggforest(fit.coxph1_2, data = Survival.data2)
fit.coxph1_2

fit.coxph2_2 <- coxph(surv_object2 ~ Treatment + Genotype, data = Survival.data2)
ggforest(fit.coxph2_2, data = Survival.data2)
fit.coxph2_2
summary(fit.coxph2_2)
```
