---
title: "Mortality of Ofav and Ssid under nutrients and heat stress"
author: "Ana Palacio-Castro"
date: "April 1, 2020"
output:
  html_document:
    fig_height: 7
    fig_width: 10
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# General project set-up 

```{r libraries, results="hide"}

# Load all libraries and sources required to run the script
    library(tidyverse)
    library(ggthemes)
    library(survival)
    library(survminer)
    #library(rms)
   
# Default ggplot settings

    Fill.colour<-c("black", "gray70", "gray35")

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

Try survival package

# 1. Ssid data

```{r}
# Data

    Survival.Ss.data<-read.csv("Data/Ssid_Mortality.csv", header = TRUE)
    summary(Survival.Ss.data)
    Survival.Ss.data$Genotype<-factor(Survival.Ss.data$Colony, levels = c(
      "Ss_22", "Ss_23", "Ss_27", "Ss_28", "Ss_24", "Ss_30", "Ss_20"))
    summary(Survival.Ss.data$Genotype)
```

```{r}
## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object_SS <- Surv(time = Survival.Ss.data$Fu.time_texp, 
                         event = Survival.Ss.data$Fu.stat_exp)
  surv_object_SS 

# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0 <- survfit(surv_object_SS ~ Genotype, conf.type = "log-log", data = Survival.Ss.data)
    summary(fit0)
  # Plot the survival model
    Genotype_only_SS<-ggsurvplot(fit0, data = Survival.Ss.data, pval = TRUE,
               risk.table=T, tables.height=0.4, conf.int = T, n.risk   = TRUE )
    Genotype_only_SS

# Only treatment model
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit1 <- survfit(surv_object_SS ~ Treatment, data = Survival.Ss.data)
    summary(fit1)
    #coxfit <- coxph(surv_object_SS ~ Treatment, data = Survival.data, ties = 'exact')
    #summary(coxfit)

    # Plot the survival model
    Treatment_Only<-ggsurvplot(fit1, data = Survival.Ss.data, pval = TRUE, 
           conf.int = T, risk.table=T, palette=Fill.colour,
           break.time.by=15, xlim=c(0,115), risk.table.y.text = FALSE,
           risk.table.title="Number of fragments at risk")
    Treatment_Only
    
# Treatment and genotype model 1 
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit2 <- survfit(surv_object_SS ~ Genotype + Treatment, data = Survival.Ss.data)
    summary(fit2)
    # Plot the survival model
    
    #GenTre_1<-ggsurvplot(fit2, data = Survival.Ss.data, pval = TRUE,
     #      risk.table=T,  tables.height=0.5)
    #GenTre_1
    
    # ggsurvplot_facet(fit2, data = Survival.Ss.data, facet.by="Genotype", 
    #                  #risk.table=T, tables.height=0.5, 
    #              nrow = 6, alpha=1,
    #              palette=Fill.colour, linetype=1)


    Ssid_PLot<-ggsurvplot_facet(fit2, data = Survival.Ss.data, 
                 facet.by="Treatment", 
                 # risk.table=T, tables.height=0.5, 
                 nrow = 3, alpha=0.5, conf.int = T,
                 linetype=1) +theme(legend.position = "left")
    
    Ssid_PLot
    

```


# 2. Ofav data

```{r}
# Data
    Survival.Of.data<-read.csv("Data/Ofav_Mortality.csv", header = TRUE)

    summary(Survival.Of.data)
    Survival.Of.data$Genotype<-factor(Survival.Of.data$Colony, 
                                      levels = c("Of_34", "Of_20", "Of_6", "Of_31"))
    summary(Survival.Of.data$Genotype)
```

```{r}
## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object_Of <- Surv(time = Survival.Of.data$Fu.time_texp, 
                         event = Survival.Of.data$Fu.stat_exp)
  surv_object_Of 

# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit4 <- survfit(surv_object_Of ~ Genotype, conf.type = "log-log", data = Survival.Of.data)
    summary(fit4)
  # Plot the survival model
    Genotype_only_OF<-ggsurvplot(fit4, data = Survival.Of.data, pval = TRUE,
               risk.table=T, tables.height=0.4, conf.int = T, n.risk   = TRUE )
    Genotype_only_OF

# Only treatment model
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit5 <- survfit(surv_object_Of ~ Treatment, data = Survival.Of.data)
    summary(fit5)
    #coxfit <- coxph(surv_object_Of ~ Treatment, data = Survival.data, ties = 'exact')
    #summary(coxfit)

    # Plot the survival model
    Treatment_Only<-ggsurvplot(fit5, data = Survival.Of.data, pval = TRUE, 
           conf.int = T, risk.table=T, palette=Fill.colour,
           break.time.by=15, xlim=c(0,115), risk.table.y.text = FALSE,
           risk.table.title="Number of fragments at risk")
    Treatment_Only
    #ggsave("Outputs/Fig_SX3_Surv_Treatment_Of.svg", 
          #Treatment_Only$plot, width=4, height=3.5,dpi = 300)
    #ggsave("Outputs/Fig_SX4_Surv_Treatment_Of.pdf", print(Treatment_Only),
           #width=5, height=6,dpi = 300)


# Treatment and genotype model 1 
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit6 <- survfit(surv_object_Of ~ Genotype + Treatment, data = Survival.Of.data)
    summary(fit6)
    # Plot the survival model
    # GenTre_1<-ggsurvplot(fit6, data = Survival.Of.data, pval = TRUE,
    #        risk.table=T,  tables.height=0.5, conf.int = T)
    # GenTre_1
    # 
    # ggsurvplot_facet(fit6, data = Survival.Of.data, facet.by="Genotype", 
    #                  #risk.table=T, tables.height=0.5, 
    #              nrow = 4, alpha=1,
    #              palette=Fill.colour, linetype=1)


   Ofav_PLot<- ggsurvplot_facet(fit6, data = Survival.Of.data, 
                 facet.by="Treatment", 
                 # risk.table=T, tables.height=0.5, 
                 nrow = 3, alpha=0.5, conf.int = T,
                 linetype=1)+theme(legend.position = "left")
   Ofav_PLot
    
# Treatment and genotype model 2
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit7 <- survfit(surv_object_Of ~ Tre_Gen, data = Survival.Of.data)
    summary(fit7)
    # Plot the survival model
    #ggsurvplot(fit7, data = Survival.Of.data, pval = TRUE, conf.int = F,
    #       risk.table=T,  tables.height=0.5)
    

```

## 2. Cox

```{r}
# fit.coxph0_3 <- coxph(surv_object_Of ~ Genotype, data = Survival.Of.data)
# HazardRatio<-ggforest(fit.coxph0_3, data = Survival.Of.data)
# fit.coxph0_3
    
fit.coxph1_3 <- coxph(surv_object_Of ~ Treatment, data = Survival.Of.data)
ggforest(fit.coxph1_3, data = Survival.Of.data)
fit.coxph1_3

# fit.coxph2_3 <- coxph(surv_object_Of ~ Treatment + Genotype, data = Survival.Of.data)
# ggforest(fit.coxph2_3, data = Survival.Of.data)
# fit.coxph2_3
# summary(fit.coxph2_3)
```


# 3. Supplementary plot

```{r}
SuplementatySurvivalA<-ggarrange(Genotype_only_OF$plot,Genotype_only_SS$plot,
                                 Genotype_only_OF$table ,Genotype_only_SS$table,
                                 labels = c("a.", "b."),
                                 ncol = 2, nrow = 2)
SuplementatySurvivalA

SuplementatySurvivalB<-ggarrange(Ofav_PLot, Ssid_PLot, labels = c("a.", "b."),
          ncol = 2, nrow = 1)
SuplementatySurvivalB


#ggsave("Outputs/Fig_S3_Surv_Treatment.svg", SuplementatySurvivalA, 
 #          width=9, height=7,dpi = 300)

#ggsave("Outputs/Fig_S3b_Surv_Treatment.svg", SuplementatySurvivalB, 
#           width=8, height=5,dpi = 300)


```
