---
title: "Raw Fv/Fm"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
    theme: united
bibliography: packages.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7)
```

# Metadata

```{r, metadata}

# Symbionts 
  SH.data<-read.csv("YII_Data/All_SPP_SH_cell_ratio_Community.csv", header = T)

## Acer Genotype information
  MOTE<-read.csv("YII_Data/Genotypes_mote.csv", header = TRUE)
      
## Timepoints information  
  TimePoints<-read.csv("YII_Data/Time_Points.csv", header = TRUE)
  TimePoints$Date<-as.Date(TimePoints$Date, "%m/%d/%y")

```

# YII values 

```{r data}
# Acer
    YII.Acer<-read.csv("YII_Data/YII_Nutrients_Acer.csv", header = T)
      YII.Acer$Fragment<-as.character(YII.Acer$Fragment)  # Fragment ID to character
      YII.Acer<-subset(YII.Acer, Colony!="F")
      YII.Acer<-subset(YII.Acer , Treatment!="Dead")
      YII.Acer$Spp<-"Ac"
    ## Genotype information
      MOTE<-read.csv("YII_Data/Genotypes_mote.csv", header = TRUE)
      YII.Acer<-merge(YII.Acer, MOTE, by="Colony", all.x=TRUE)

# Ofav    
    YII.Ofav<-read.csv("YII_Data/YII_Nutrients_Ofav.csv")
      YII.Ofav$Fragment<-as.character(YII.Ofav$Fragment) 
      YII.Ofav$Colony<-factor(as.character(YII.Ofav$Colony), 
                            levels=c("31","6","20","34"))  # D dominance order
      YII.Ofav$Genotype<-paste("Of", YII.Ofav$Colony, sep = "_")
      YII.Ofav$Spp<-"Of"

            
# Ssid      
    YII.Ssid<-read.csv("YII_Data/YII_Nutrients_Ssid.csv")
      YII.Ssid$Colony<-factor(as.character(YII.Ssid$Colony), 
                                 levels=c("30","20","24","28","22","23","27") )  # D dominance order
      YII.Ssid$Genotype<-paste("Ss", YII.Ssid$Colony, sep = "_")
      YII.Ssid$Spp<-"Ss"
      
# Pool all species the data
      YII.data<-dplyr::bind_rows(list(YII.Acer,YII.Ofav,YII.Ssid))
      YII.data<-YII.data[,-1]
      summary(YII.data)
      
```

# Merge/Transform

```{r}
# Organize data type
      YII.data$Date<-as.Date(YII.data$Date, "%m/%d/%y")
      YII.data$Days<-(as.numeric(YII.data$Date) -17485)
      
      YII.data$Spp <- as.factor(YII.data$Spp)
      
      YII.data$Treatment[YII.data$Treatment == "Control"] <- "A"
      YII.data$Treatment[YII.data$Treatment == "NP"] <- "N+P"
      YII.data$Treatment <- as.factor(YII.data$Treatment)
      
      YII.data$Genotype<-factor(as.character(YII.data$Genotype), 
                             levels=c("G_48", "G_62","G_31", 
                                      "G_08","G_07", "G_50", 
                            "Of_34","Of_20","Of_6", "Of_31",
                            "Ss_22","Ss_23","Ss_27", "Ss_28",
                            "Ss_20", "Ss_24","Ss_30"
                             ))  # D dominance order
      
      
      YII.data<-merge(YII.data, TimePoints, by="Date", all.x=TRUE)
      
      YII.data$Fragment <- paste(YII.data$Spp, YII.data$Fragment, sep = "_")
      YII.data$SampleID <- paste(YII.data$Fragment, YII.data$Time, sep = "_")
      YII.data$Sample <- paste(YII.data$Fragment, YII.data$Time_Point, sep = "_")
      
# Add symbiont community
      YII.data<-merge(YII.data, SH.data, by="Sample", all.x=TRUE)
      
# Check the data
      str(YII.data)
      summary(YII.data)
      # YII.data<-YII.data[order(
      #   YII.data$Spp, YII.data$Treatment, YII.data$Replicate,
      #   YII.data$Fragment, YII.data$Date),]
      YII.data<-YII.data[order(
        YII.data$Spp, YII.data$Fragment, YII.data$Date, 
        YII.data$Treatment, YII.data$Replicate
        ),]
      #write.csv(YII.data, "Outputs/All_YII_data.csv", row.names = F)
    
   
```

