---
title: "Changes in Fv/Fm in elevated nutrients and heat stress (Only *A.cer*)"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
    theme: united
bibliography: packages.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7)
```


# General project set-up 

```{r libraries, results="hide"}

# Load libraries and sources required to run the script
    library(tidyverse)
    library(ggthemes)
    library(lmerTest)
    library(emmeans)
    library(multcomp)
    library(effects)

# Default ggplot settings

    Fill.colour<-scale_colour_manual(values = c("black", "gray70", "gray35"))

    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
```

# Data exploration

##  1. Get the files with all the YII by species

```{r data}
# Acer
    YII.Acer<-read.csv("YII_Data/YII_Nutrients_Acer.csv", header = T)
      YII.Acer$Fragment<-as.character(YII.Acer$Fragment)  # Fragment ID to character
      YII.Acer<-subset(YII.Acer, Colony!="F")
      YII.Acer<-subset(YII.Acer , Treatment!="Dead")
      YII.Acer$Spp<-"Ac"
    ## Genotype information
      MOTE<-read.csv("YII_Data/Genotypes_mote.csv", header = TRUE)
      YII.Acer<-merge(YII.Acer, MOTE, by="Colony", all.x=TRUE)

# Ofav    
    YII.Ofav<-read.csv("YII_Data/YII_Nutrients_Ofav.csv")
      YII.Ofav$Fragment<-as.character(YII.Ofav$Fragment) 
      YII.Ofav$Colony<-factor(as.character(YII.Ofav$Colony), 
                            levels=c("31","6","20","34"))  # D dominance order
      YII.Ofav$Genotype<-paste("Of", YII.Ofav$Colony, sep = "_")
      YII.Ofav$Spp<-"Of"

            
# Ssid      
    YII.Ssid<-read.csv("YII_Data/YII_Nutrients_Ssid.csv")
      YII.Ssid$Colony<-factor(as.character(YII.Ssid$Colony), 
                                 levels=c("30","20","24","28","22","23","27") )  # D dominance order
      YII.Ssid$Genotype<-paste("Ss", YII.Ssid$Colony, sep = "_")
      YII.Ssid$Spp<-"Ss"
      
# Pool all species the data
      YII.data<-dplyr::bind_rows(list(YII.Acer,YII.Ofav,YII.Ssid))
      YII.data<-YII.data[,-1]
      summary(YII.data)
      
# Organize data type
      YII.data$Date<-as.Date(YII.data$Date, "%m/%d/%y")
      YII.data$Days<-(as.numeric(YII.data$Date) -17485)
      
      YII.data$Spp <- as.factor(YII.data$Spp)
      YII.data$Treatment[YII.data$Treatment == "Control"] <- "A"
      YII.data$Treatment[YII.data$Treatment == "NP"] <- "N+P"
      YII.data$Treatment <- as.factor(YII.data$Treatment)
      YII.data$Genotype<-factor(as.character(YII.data$Genotype), 
                             levels=c("G_48", "G_62","G_31", 
                                      "G_08","G_07", "G_50", 
                            "Of_34","Of_20","Of_6", "Of_31",
                            "Ss_22","Ss_23","Ss_27", "Ss_28",
                            "Ss_20", "Ss_24","Ss_30"
                             ))  # D dominance order
      YII.data$Fragment <- paste(YII.data$Spp, YII.data$Fragment, sep = "_")
      YII.data$SampleID <- paste(YII.data$Fragment, YII.data$Time, sep = "_")
      
# Check the data
      str(YII.data)
      summary(YII.data)
      # YII.data<-YII.data[order(
      #   YII.data$Spp, YII.data$Treatment, YII.data$Replicate,
      #   YII.data$Fragment, YII.data$Date),]
      YII.data<-YII.data[order(
        YII.data$Spp, YII.data$Date, YII.data$Treatment, YII.data$Replicate,
        YII.data$Fragment),]
      #write.csv(YII.data, "Outputs/All_YII_data.csv", row.names = F)
    
    # Remove baseline values
      YII.data<-subset(YII.data, Days>-1)
    # Remove recovery values
      YII.data<-subset(YII.data, Days<112)
      # write.csv(YII.data, "Outputs/Experiment_YII_data.csv", row.names = F)  
    # YII.Wide<- reshape(YII.data, idvar = "Fragment", timevar = "Days", direction = "wide")
      
      Spp.fragments<-YII.data %>% 
        group_by(Spp, Genotype, Treatment, Replicate) %>% count(Fragment)
      Spp.fragments
      #write.csv(Spp.fragments, "Outputs/Meassurments_perFragments.csv", row.names = F)

# Subset data before heat stress (Only nutrients)
      YII.nutrients<-subset(YII.data, Days<80)
```

## 2. Exploratory graphs

All time points (nutrients + heat stress)

* Colony (Genotype) differences

```{r explore}
YII_Colony<- ggplot(YII.data, aes (Days, YII, colour=Genotype)) +
        stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.5)+
        stat_summary(fun.y=mean, geom="line", alpha=0.6) +   theme_bw()
      YII_Colony + ylim(0.0, 0.65) + facet_grid (Spp~Treatment)
      
YII_Frag_Gen<- ggplot(YII.data, aes (Days, YII, colour=Genotype, group=Fragment)) +
        stat_summary(fun.y=mean, geom="line", alpha=0.5) +  
        theme_bw() + theme(legend.position = "bottom",
                           legend.title = element_blank())
      YII_Frag_Gen + ylim(0.0, 0.65) + facet_grid (Spp~Treatment)
```

* Treatment differences 

```{r treatmentcolours}
YII_Treat<- ggplot(YII.data, aes (Days, YII, colour=Treatment)) +
        stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2, position = position_dodge(1) )+ ggthe_bw+
        stat_summary(fun.y=mean, geom="point")  +
        theme(legend.position="bottom",
              strip.background = element_rect(fill="white"))+
        scale_y_continuous(limits = c(0, 0.7),
                           breaks = seq(0, 0.6, 0.1),  
                           expand = c(0, 0),
                           name=("Fv/Fm")) +
        scale_x_continuous(name="Days in the experiment",
                           limits = c(-1,113),
                           breaks = seq(0, 113, 15),  
                           expand = c(0, 0))+
        annotate("segment", x = 2, xend = 91, y = 0.12, yend = 0.12,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 79, xend = 91, y = 0.12, yend = 0.20,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 91, xend = 110, y = 0.20, yend = 0.20,
                  colour = "gray90", linetype=1)+
        annotate("text", x = 45, y = 0.15, label = "Nutrients", size=3)+
        annotate("text", x = 99, y = 0.15, label = "Heat", size=3)
YII_Treat + facet_grid (~Spp) + geom_smooth()

YII_Treat + facet_wrap (Genotype~Spp) + geom_smooth()

```

# Figure 3b (Only A.cervicornis)

```{r Figure, fig.height = 3, fig.width = 3.5}
YII_Treat_BW<- ggplot(data=subset(YII.data, Spp=="Ac"), aes (Days, YII, colour=factor(Treatment), shape=factor(Treatment))) + ggtitle("b") +
        ggthe_bw + Fill.colour+
        stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 1,
                     position = position_dodge(1) )+
        stat_summary(fun.y=mean, geom="line", position = position_dodge(1), 
                     linetype=1, alpha=1) + 
         stat_summary(fun.y=mean, geom="point", size =1,
                   position=position_dodge(width=1), alpha=0.8)  +
        theme(legend.position=c(0.2, 0.5),
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) + # geom_smooth()+
      
    scale_y_continuous(limits = c(0.1, 0.7),
                           breaks = seq(0.1, 0.6, 0.1),  
                           expand = c(0, 0),
                           name=expression(~italic("Fv / Fm"))) +
        scale_x_continuous(name="Days in the experiment",
                           limits = c(-1,113),
                           breaks = seq(0, 113, 15),  
                           expand = c(0, 0))+
        annotate("segment", x = 2, xend = 91, y = 0.12, yend = 0.12,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 79, xend = 91, y = 0.12, yend = 0.20,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 91, xend = 110, y = 0.20, yend = 0.20,
                  colour = "gray90", linetype=1)
        
      
      Figure3<-YII_Treat_BW + #facet_grid (Spp~.)+
        annotate("text", x = 45, y = 0.15, label = "Nutrients", size=3)+
        annotate("text", x = 99, y = 0.15, label = "Heat", size=3)
Figure3
#ggsave(file="Outputs/Fig_3b_Acer_YII_Treat.svg", plot=Figure3, width=3.5, height=3)
```

* Genotype G07 was especially unhappy in ambient nutrients... 

```{r}
YII_Treat_BW<- ggplot(data=subset(YII.data, Spp=="Ac"), aes (Days, YII, colour=factor(Genotype))) +
        ggthe_bw + 
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 1,
                     position = position_dodge(1) )+
  stat_summary(fun.y=mean, geom="line", position = position_dodge(1), linetype=1, alpha=1) + 
  stat_summary(fun.y=mean, geom="point", size =1,
                   position=position_dodge(width=1), alpha=0.8)  +
  theme(legend.position="bottom", 
              legend.title = element_blank(),
              strip.background = element_rect(fill="white"))+
  scale_y_continuous(limits = c(0.1, 0.7),
                           breaks = seq(0.1, 0.6, 0.1),  
                           expand = c(0, 0),
                           name=expression(~italic("Fv / Fm"))) +
  scale_x_continuous(name="Days in the experiment",
                           limits = c(-1,113),
                           breaks = seq(0, 113, 15),  
                           expand = c(0, 0))+
  annotate("segment", x = 2, xend = 91, y = 0.12, yend = 0.12,
                  colour = "gray90", linetype=2)+
  annotate("segment", x = 79, xend = 91, y = 0.12, yend = 0.20,
                  colour = "gray90", linetype=4)+
  annotate("segment", x = 91, xend = 110, y = 0.25, yend = 0.20,
                  colour = "gray90", linetype=3)
        
      
   Figure3<-YII_Treat_BW + facet_grid (~Treatment)+
        annotate("text", x = 45, y = 0.2, label = "Nutrients", size=3)+
        annotate("text", x = 99, y = 0.2, label = "Heat", size=3)
Figure3
```


# Figure S3b: Treatment effect by genotype

```{r FigureSupple,  fig.height = 7, fig.width = 8}

FigureS3_genotype<-YII_Treat_BW<- ggplot(data=subset(YII.data, Spp=="Ac"), aes (Days, YII, colour=factor(Treatment), shape=factor(Treatment))) +
        ggthe_bw + Fill.colour+
        stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 5,
                     position = position_dodge(1) )+
        stat_summary(fun.y=mean, geom="line", position = position_dodge(1), 
                     linetype=1, alpha=1) + 
         stat_summary(fun.y=mean, geom="point", size =1,
                   position=position_dodge(width=1), alpha=0.5)  +
        theme(axis.title.y=element_text(size=12), 
          legend.position="bottom",
          legend.title = element_blank()) + ggtitle("b") +
      
    scale_y_continuous(limits = c(0.0, 0.7),
                           breaks = seq(0.0, 0.6, 0.1),  
                           expand = c(0, 0),
                           name=expression(~italic("Fv / Fm"))) +
        scale_x_continuous(name="Days in the experiment",
                           limits = c(-1,113),
                           breaks = seq(0, 113, 30),  
                           expand = c(0, 0))+
        annotate("segment", x = 2, xend = 91, y = 0.12, yend = 0.12,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 79, xend = 91, y = 0.12, yend = 0.20,
                  colour = "gray90", linetype=1)+
        annotate("segment", x = 91, xend = 110, y = 0.20, yend = 0.20,
                  colour = "gray90", linetype=1)+
        annotate("text", x = 45, y = 0.05, label = "Nutrients", size=3)+
        annotate("text", x = 99, y = 0.05, label = "H", size=3) +
  facet_grid(~Genotype)
FigureS3_genotype
  
#ggsave(file="Outputs/S3b_YII_Treat_Colo.svg", plot=Figure3_genotype, width=6.0, height=3.5)
```

# YII GLMs

## All spp pooled

```{r models}
#Time as a factor, not as int
      str(YII.data)
      YII.data$DaysF<-as.factor(YII.data$Days)

# All spp together
      LME1<-lmer(YII ~ Treatment * DaysF * Spp + (1|Genotype),
                REML=TRUE, data=YII.data, na.action=na.omit)
       lmerTest::step (LME1)
       drop1(LME1, test = "Chisq")
       summary(LME1)
       # plot(Effect(c("Treatment","Spp","DaysF"), LME1), x.var="DaysF", multiline=T, ci.style="bars",
       #    ylab="Fv/Fm", xlab="Days in the experiment")
    
      # EMMs
      All.YII.emm<-emmeans(LME1, ~Treatment * DaysF* Spp)
      emmip(LME1, ~DaysF|Treatment|Spp, CIs = TRUE) + theme_bw() + facet_grid(Spp~Treatment)
  # Spp responded differently, do separate analysis for each one
```

## A.cer model

```{r Acer_models}
  
# 1. Find the best model

LME_Acer<-lmerTest::lmer(YII ~ Treatment * DaysF + 
                             (1|Genotype) + (1|Replicate) +  (1|Fragment), 
                              data=subset(YII.data, Spp=="Ac"), na.action=na.omit)
      summary(LME_Acer)
      
      Step.LME_Acer<-step (LME_Acer) # Replicate is not significant
      anova(LME_Acer)
      ranova(LME_Acer)# Replicate is not significant
      # Drop (1|Replicate)
      final_fm <- get_model(Step.LME_Acer)
      summary(final_fm)
      
  LME_Acer1<-lmerTest::lmer(YII ~ Treatment * DaysF + 
                             (1|Genotype/Fragment), 
                              data=subset(YII.data, Spp=="Ac"), na.action=na.omit)
      
  ranova(LME_Acer1)
  
  LME_Acer2<-lmerTest::lmer(YII ~ Treatment * DaysF + 
                             (1|Genotype) +  (1|Fragment), 
                              data=subset(YII.data, Spp=="Ac"), na.action=na.omit)
  ranova(LME_Acer2)    
  
  anova(LME_Acer1, LME_Acer2) # LME_Acer1 and LME_Acer2 are the same 
  
#2. Extract EMMs
      Acer.YII.emm<-emmeans(LME_Acer1, ~Treatment * DaysF)
      contrast(Acer.YII.emm, "tukey")
      
      # Effect plot options
      emmip(LME_Acer, ~DaysF|Treatment, CIs = TRUE) + theme_bw() # interaction plot of predictions
      
      # Pairwise comparisons
      #pairs(Acer.YII.emm) # same than contrast(Acer.YII.emm, "tukey")
      
      #plot(emmeans(LME_Acer, ~DaysF|Treatment), comparisons = TRUE) +
      #  coord_flip(xlim = NULL, ylim = NULL, expand = TRUE) + facet_wrap(~Treatment) +
      #  theme_gdocs() # Tukey comparison (do not trust CI to compare EMMs)
      
      Acer.YII_groups<-cld(Acer.YII.emm, by=NULL) # compact-letter display
      Acer.YII_groups<-Acer.YII_groups[order(Acer.YII_groups$Treatment, Acer.YII_groups$Day),]
      Acer.YII_groups
      write.csv(Acer.YII_groups, "Outputs/Multicomp_AcerYII.csv", row.names = F)
```

